# docker-compose.yml
version: '3'
networks:
  todoapp-net:
services:
  pythonapp:
    image: todoapp:1.2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD:-1234}
      - MYSQL_DATABASE=${NAME:-app_db}
      - MYSQL_USER=${USER:-app_user}
      - MYSQL_PASSWORD=${PASSWORD:-1234}
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql-local:1.2.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - ENGINE=${ENGINE:-mysql.connector.django}
      - NAME=${NAME:-app_db}
      - USER=${USER:-app_user}
      - PASSWORD=${PASSWORD:-1234}
      - HOST=${HOST:-mysql}
      - PORT=${PORT:-3306}
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
